### ISSUE TITLE
Let's talk about the Unid cetacean category

### ISSUE THREAD

**Issue by ybarkley** [PIFSC-Protected-Species-Division/cruise-maps-live#28]
@sfregosi @amandalbradford 

I've gotten some feedback about including the "unid cetacean" category on the map instead of the more specific unids category. For example, there was a Unid Large Whale on 8/7/23, but it's on the map as Unid Cetacean and, oh, how shameful that is! How can these observers not tell a dolphin from a whale or whale from a porpoise?!!? It feels insulting to their expert observer abilities.

I see their point, but also know there were discussions about all of these Unids and how to lump some together. Is it possible to at least include Unid Whale to be more specific, which seems to work nicely with Unid dolphin. I think Unid Cetacean is the absolute last resort ID. 

Let me know what you think and if this would work for the map. I don't know the background to the lumping decisions, so please fill me in, thanks!

**Comment by amandalbradford** [comment]
Hi @ybarkley - I think we decided to lump based on the groupings I use for analysis:

“Unidentified dolphins”
177 - Unidentified small dolphins
277 - Unidentified medium dolphins
377 - Unidentified large dolphins
077 - Unidentified dolphins
“Unidentified cetaceans”
078 - Unidentified small whales
079 - Unidentified large whales
098 - Unidentified whales
096 - Unidentified cetaceans

To me, the unid whale categories are so ambiguous because they could be odontocetes or mysticetes (thus the lumping as unid cetaceans for analysis), but I definitely see the observers point for this purpose. I would have no problem lumping 078, 079, and 098 as unid whales and keeping 096 separate as unid cetacean. Would the observers be supportive of that? 

I'm also not opposed to going to the raw unid level, but it's a trade-off with legend real estate, so maybe @sfregosi can speak to that. It's awesome to get feedback from them!

**Comment by ybarkley** [comment]
Thank you both! This plan sounds great and will make the observers very happy :)
If the legend starts getting packed, we can reassess the lumping strategy. Thank you!

**Comment by amandalbradford** [comment]
Thanks y'all, I think that sounds like a good plan - "going with the 78/79/98 group and keeping unid cetacean/96 out." As for the other groupings, a couple notes:

Unid beaked whale (49, 149) - ALB: I don't believe 149 has been used in our data yet, but this is reasonable
Unid cetacean (96)
Unid dolphin (77, 177, 277, 377)
Unid marine mammal (197) - ALB: I don't think this will get used, probably no need to devote an icon
Unid Mesoplodon (51) - SF: maybe we want to just lump this with beaked whales but see what they think? ALB: Good to ask them, I could see them wanting to keep this separate since it's closer to a species.
Unid object (97) - ALB: I don't think this will get used, nor that we should map it if it ever does
Unid rorqual (70, 99, 199) - ALB: Good to ask them, I could see them wanting to pull out 99 (sei/Bryde's) because it's so specific
Unid whale (78, 79, 98)

There's also Unid Kogia (80) - that will likely get used! Thanks for the diligence!

**Comment by sfregosi** [comment]
The changes for Unid whale are in place (and now plotting as dark grey diamond) so I'm going to close this for now, but feel free to reopen (or make a new issue) if other suggested grouping changes come up!

I'm going to make some time zone changes (#29) so in that I will also put a catch to *NOT* plot any 97/Unid objects
