### ISSUE TITLE
Map legend is cut off

### ISSUE THREAD

**Issue by ybarkley** [PIFSC-Protected-Species-Division/cruise-maps-live#30]
@sfregosi @badgerjj 

I noticed the map legend is cut off as it is getting longer with more species. 
Maybe just a tweak to the margins? Hopefully!
![814-dailyMap_visuals](https://github.com/PIFSC-Protected-Species-Division/cruise-maps-live/assets/11492451/263e9c19-328b-44a1-a779-e1731767aede)

**Comment by sfregosi** [comment]
Good catch @ybarkley. 

When I made the 'max' map with all possible sightings it expanded the legend into two columns, which totally messed up the size of the map. I was able to get around this by just printing it at twice the size (20 wide by 10 tall instead of 10 in wide by 5 in tall). 

I could try to just resize it that way, but will hold off to see if @badgerjj has any other insight since she had so much fun with playing with sizing when building the mapping function :)

**Comment by badgerjj** [comment]
Haha. I would say if the number of species were to vary we could make a function to size the map according to needs, but as it just grows I think Selene’s suggestion works great! Janelle J. Badger, Ph.DStatistician/Research Ecologist, Cetacean Research ProgramNOAA Fisheries | Pacific Islands Fisheries Science CenterOn Aug 14, 2023, at 5:13 PM, sfregosi ***@***.***> wrote:﻿
Good catch @ybarkley.
When I made the 'max' map with all possible sightings it expanded the legend into two columns, which totally messed up the size of the map. I was able to get around this by just printing it at twice the size (20 wide by 10 tall instead of 10 in wide by 5 in tall).
I could try to just resize it that way, but will hold off to see if @badgerjj has any other insight since she had so much fun with playing with sizing when building the mapping function :)

**Comment by sfregosi** [comment]
Ok I've got a workable solution that I'm not *totally* happy with but it will hold us over for a while. 

**Temporary Solution**
- Added a `nrow` argument to the legend so now it will only list up to 13 species per legend column, which is the number that will fit for our current 5 inch print height, since we know that renders nicely on the site
- When it goes to multiple columns, but the print width is held at 10 inches, that shrinks the actual map plotting area to make room for more legend entries so built in a if/else to print the size based on the number of columns (which is based on total number of species sighted). Print width will go up with more columns
- Each time a map crosses the species threshold to add another column, it will need to be manually updated on the website (the web content holder is expecting an image of a specific size). 

**Remaining Issue**
- The scaling of the actual print area is largely out of our control. I went on a pretty deep SO and ggplot dive and found answers like 'its not possible'. I might still ask there in case there are recent functionality improvements...but will need to have time for that
- For example, the acoustic plot includes a detection of Cross Seamount beaked whale. That is a long name, so the legend width of the acoustic figure is wider than the legend width of just a single column visual plot legend. Holding print sizes the same, the actual plot area is slightly different between these two single column legend plots. In fact, that is the case between acoustic plots PRE CSBW and POST CSBW.  
- This isn't a huge deal, it just bothers my perfectionism of wanting everything to line up perfectly. It also means that making a gif might be off the table. Again not the end of the world but something to maybe think forward about. 

**Possible Further Solutions**
- move the legend to below the plot (if this is possible?) This would still take a lot of fine tuning to get all the sizes correct, but the number of legend columns could be set and the 'growth' as more were added may be more predictable since it would be lines being added (which are a known font size/height) rather than legend columns that can vary in width. But, this will take a lot of work and perhaps not worth it. Also may be complicated to do this with the track legend. 
- Create a separate static figure that has the legend items. Could even just post 1 for both plots. It could have all possible species. Then map outputs would be the MAP alone.

**Comment by ybarkley** [comment]
I think the if/else to make the map size grow based on number of columns is our best solution. 
No need to spend more time on this :) 
I'll check whether I need to manually change things on the website once we add columns.
Thank you @sfregosi for your deep diving on this matter!

**Comment by sfregosi** [comment]
thanks @ybarkley I just pushed all the changes (also re-ran 812 because @mchill808 said she updated it) so we can see how it looks on the site now!
