### ISSUE TITLE
Remove Acoustic Detections from table

### ISSUE THREAD

**Issue by ybarkley** [PIFSC-Protected-Species-Division/cruise-maps-live#7]
@sfregosi Can you remove the column for acoustic detections until we get that working? 
It comes across as no data from them at the moment.

**Comment by sfregosi** [comment]
Fixed this with [18ef158](https://github.com/PIFSC-Protected-Species-Division/cruise-maps-live/commit/18ef15813f5ce4f3792d07c9385a5d57b30daecc) but this renders oddly on the website now. Probably because the aspect ratio of the table is different now. 

Will relink on web and publish and see if that fixes it.

**Comment by sfregosi** [comment]
ok fixed on the web too. Closing!
